### ISSUE TITLE
[DCIC Book]: please enter a brief summary here

### ISSUE THREAD

**Issue by DavidCooperWCU** [data-centric-computing/dcic-public#17] opened 2022-01-08 14:49 UTC
### Contact Details

dcooper@wcupa.edu

### Which Web page has the problem?

https://dcic-world.org/2021-08-21/part_state.html#%28part._.Modifying_.Variables_in_.Memory%29

### What's the problem?

After:

> Directory
> run_total → 5
> num → 5

There is a loose closing square bracket:

]

### What browser are you seeing the problem on?

Safari

**Comment by sorawee** [comment] 2022-01-13 05:34
This is a duplicate of #10. IIUC, It's already fixed, but the fix is not released yet.

**Closed** 2022-01-15 20:06 UTC
